### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by PostBird12** [anik123/Android-Carousel-with-Circular-Image-and-Card#1]
Facing the following exception  on case list size=1

java.lang.IllegalArgumentException: position can't be great then adapter items count. position is : 2
                                                                         at com.azoft.carousellayoutmanager.CarouselLayoutManager$1.computeScrollVectorForPosition(CarouselLayoutManager.java:199)
                                                                          at android.support.v7.widget.LinearSmoothScroller.updateActionForInterimTarget(LinearSmoothScroller.java:232)
                                                                          at android.support.v7.widget.LinearSmoothScroller.onSeekTargetStep(LinearSmoothScroller.java:140)
                                                                          at android.support.v7.widget.RecyclerView$SmoothScroller.onAnimation(RecyclerView.java:11225)
                                                                          at android.support.v7.widget.RecyclerView$SmoothScroller.access$600(RecyclerView.java:11096)
                                                                          at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4923)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:655)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                          at android.os.Handler.handleCallback(Handler.java:789)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by anik123** [comment]
In your adapter, total item is 

> Facing the following exception on case list size=1

But in the code, somewhere you have set selected item index 2 which is out of index

> java.lang.IllegalArgumentException: position can't be great then adapter items count. position is : 2
